### ISSUE TITLE
[Bug] Deezer does not show album title when hovering the cover

### ISSUE THREAD

**Issue by hans-juergen** [ungive/discord-music-presence#49] opened 2024-10-07 18:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no popup info for the shown album when I hover or click on the cover in my Discord profile, only for the track and artist. Not sure if this is specific to the Deezer desktop app or maybe with all other media players as well.

### Reproduction Steps

1. Go to your Discord profile.
2. Hover or click on the shown album artwork.
3. See the error

### Expected behavior

A popup with the album title when hovering or clicking on the artwork.

### Screenshots

![image](https://github.com/user-attachments/assets/fd35126e-b673-4789-ad4f-c4c5735dcdf4)

### Additional context

Also the duration of the track is not shown as a progress bar like in the example screenshot, but only the played time, not the total time as well.

Is it correct that the app will neither work with the Discord browser interface nor the Deezer web player, but only with their desktop apps?

**Comment by ungive** [comment] 2024-10-07 18:42
(I assume you're on Windows) That is because Deezer does not report any album title:

```
AppUserModelId: Deezer.exe
Title: A Bar Song (Tipsy)
Subtitle: <empty>
Artist: Shaboozey
AlbumTitle: <empty>
AlbumArtist: <empty>
PlaybackStatus: Playing
Position (live): 13372799808468ms
Position (fixed): 0ms
LastUpdatedTime: -11644473600000ms
EndTime - StartTime (duration): 0ms
MinSeekTime: 0ms
MaxSeekTime: 0ms
MaxSeekTime - MinSeekTime (duration): 0ms
PlaybackType: Music
TrackNumber: 0
AlbumTrackCount: 0
Genres:
```

You can verify this yourself using this little program (which generated the above output): https://github.com/ungive/media-session-dump/releases. It gets its information from the same source as Music Presence.

You should report this issue to Deezer. Deezer basically reports nothing useful to Windows (using "SystemMediaTransportControls"/"SMTC" via WinRT APIs) except the song title, artist and whether it's playing or not. The rest of the values are basically not set.

What I could do is use the Deezer API to guess the album name. That is what I do with TIDAL, which also doesn't report the album name on Windows. This wouldn't show the correct album in some cases though. Is that something you'd welcome as an addition?

**Comment by hans-juergen** [comment] 2024-10-07 18:51
Thanks for the quick reply. Yes, I'm on Windows 10 Pro currently using the Deezer desktop app and would like to be able to see the album title either when hovering or clicking on it. Even better would be a direct link to the album page in Deezer, but that may be impossible or too much work. 😉

Usually I don't use the Deezer desktop app, as it does not provide gapless playback like their web player, but as far as I have understood the FAQs, web players of streaming services are not supportable by your app?

**Comment by ungive** [comment] 2024-10-07 21:42
> Thanks for the quick reply. Yes, I'm on Windows 10 Pro currently using the Deezer desktop app and would like to be able to see the album title either when hovering or clicking on it. Even better would be a direct link to the album page in Deezer, but that may be impossible or too much work. 😉

If it isn't too much work I'll add it with the next update, otherwise the update after that!

> Usually I don't use the Deezer desktop app, as it does not provide gapless playback like their web player, but as far as I have understood the FAQs, web players of streaming services are not supportable by your app?

Technically Music Presence detects media from your browser as well and it would be possible to show it in your status. The problem is that there's no way to differentiate which website that media is coming from, so I can't reliably determine if it's e.g. music from Deezer that you wanna show in your status or e.g. a learning video from the university you're studying at which you definitely don't want to share in your status.

I have started working on a browser extension a few months ago which I'll pick up on at some point again when I find the time and it becomes a higher priority than other features I am working on. More info in issues #5.

**Comment by hans-juergen** [comment] 2024-10-09 11:19
By the way, the shown album artwork always seems to be correct, I wonder from where your app gets them from if not available in the Deezer desktop app?

**Comment by ungive** [comment] 2024-10-09 13:02
I forgot to mention Deezer also reports the album image, which is what is displayed in your status.

I've implemented the Deezer API yesterday to get the album title and song duration:

![image](https://github.com/user-attachments/assets/f5d8289c-bc84-4011-a24b-6985e4e7dc30)

I'll also filter out ads, seems like they are always formatted this way:

![image](https://github.com/user-attachments/assets/34dbe386-c8fe-405e-9d19-d150c44a31e1)

**Comment by ungive** [comment] 2024-10-10 23:33
Fixed in version 2.2.4

- using the Deezer API to get track info: missing album name, the song duration and a link to the song. the song duration turns the simple timestamp into a progress bar
- if the track is a podcast: getting the proper cover image and displaying it in the status. the cover image from Deezer itself is a simple podcast/microphone icon for some reason

**Closed by ungive** 2024-10-10 23:33 UTC
Labels: bug, player issue

**Comment by hans-juergen** [comment] 2024-10-13 03:50
Thank you for improving the Deezer handling in your app! I can see the album title all the time and when hovering the album artwork or title. Sometimes it is replaced by a question mark, not sure what the reason is:
![image](https://github.com/user-attachments/assets/b50c1871-3980-44ce-a5c2-7bd5fda22c53)

I cannot go directly to the song or album page in Deezer though, as there is no link to it, so other Deezer users on Discord could not listen to it as well.

Concerning blocking ads I have a Family account, so I don't see them anyhow, but a nice feature for free users, I guess. I don't listen to podcasts either, so cannot comment on your improvements there.

By the way, I posted about the new version in an internal Deezer Discord server and the Deezer subreddit yesterday, and the admin asked if there is a mobile version of Music Presence, as he mostly uses his phone for music listening like many people do nowadays. But I haven't seen plans for mobile support here yet, right?

**Comment by ungive** [comment] 2024-10-13 08:52
Yes, the question mark is most likely caused by #52

There's a Discord bug that has been there for months where you can't see buttons in your status when you're looking at your own profile on your account. Ask a friend or use a second account to check if you can see the buttons, or maybe check on your phone. There should be a "Listen to this song" button whenever you see the progress bar.

There is no mobile version yet, but maybe in the future. This is difficult though because on mobile you can't use Discord RPC or the Discord Game SDK because of technical limitations on that platform. You'd have to either use the Discord API which is against Discord ToS last time I check (called self-botting) or you'd have to connect a Music Presence mobile app to the desktop version, then send the song info from your phone to the Desktop and show that in your status. That's pretty impractical though.

The better solution would be to partner with Discord at some point, but that's probably out of reach for now. Something like Spotify x Discord, but instead Music Presence x Discord, if that makes sense. That could allow Music Presence to show a Discord status even when Discord is not running on the same device as Music Presence. Would be awesome. But I bet there might be legal caveats, the music industry is complicated.

Right now there are no plans for a mobile app because of this complication, no.

**Comment by hans-juergen** [comment] 2024-10-13 10:53
Thanks again for your replies. Did not know about that Discord bug that will not show buttons and links on your own profile, I will ask someone on my main servers. By the way, do you know the inofficial Last.fm server? They have a #help-api-tools channel where Music Presence is discussed as well: https://discord.gg/zJpPfV3h

**Comment by ungive** [comment] 2024-10-13 11:31
> By the way, do you know the inofficial Last.fm server?

I'll be sure to check it out!

You and your friends are welcome to join our Discord too btw! https://discord.com/invite/7rc8dWD4ug

My goal is to reach 1000 members to be able to add Music Presence to Discord's server discovery, which will be a big step towards getting the word out for Music Presence.

**Comment by hans-juergen** [comment] 2024-10-13 18:00
Just commented on your new message there and also joined your Discord server.

And as I just switched from Spotify to Deezer listening, I had another related idea to maybe embed the available infos in the Deezer play queue view to your app if possible, i.e. 1. the audio quality of the stream (HiFi for lossless FLAC, HQ for MP3 @ 320kbps or nothing for MP3 @ 128kbps) shown in the lower left corner of the album artwork and 2. which Mix is playing like e.g. Flow shown under the album artwork and on top of the queue:

![image](https://github.com/user-attachments/assets/833ff4b7-9c09-4ef5-af64-2ee9b717fa02)
 Maybe you can make a screenshot of my current Deezer listening how my Discord profile looks to other users?

**Comment by ungive** [comment] 2024-10-13 19:33
I'm afraid there is no way to get that information, as far as I am aware

- The track endpoint has no quality information: https://developers.deezer.com/api/track
- The flow endpoint for a user only lists tracks, but not the name of the flow. I've tested this by creating an OAuth token for my own user following these steps: https://developers.deezer.com/api/oauth and then testing the user endpoint: https://developers.deezer.com/api/user in the api explorer: https://developers.deezer.com/api/explorer
- The Deezer desktop app only reports basic information to the operating system, like title, artist and album art

If you find a way let me know!

**Comment by hans-juergen** [comment] 2024-10-15 05:39
Thank you for checking. The currently used audio quality is only shown as a grey sticker in the lower left corner of the album artwork in the play queue, nowhere else in the Deezer desktop app. So I thought this info would be available somewhere in their API. I guess you use a free account which only delivers standard audio quality (SQ=128 MP3) which is not shown on the album artwork (only HiFi or HQ), so that might be the reason why you cannot find it in the API either.

And the name of the Flow mix is always "Flow", it doesn't change, so mentioning it in your app would be a bonus, as Deezer users would know then that I am playing this special Deezer mix.
Another grey sticker available in the play queue and playbar at the bottom is "Mix" which is displayed e.g. when you start a song from the search which automatically generates a Track Mix then. Here is a screenshot of the playbar currently showing the grey "Flow" sticker as well:

![image](https://github.com/user-attachments/assets/2db00b00-2049-4755-84b0-907da11444b4)

**Comment by ungive** [comment] 2024-10-15 07:42
When I checked the flow endpoint it only reported songs that finished playing, not the current ones. So there's no way of telling if the current song is playing from a Flow or not. One could *guess*, by checking if the last song in the flow is not more than e.g. 10 minutes ago, but that would be a hack imo.

> I guess you use a free account which only delivers standard audio quality (SQ=128kbps MP3) which is not shown on the album artwork (only HiFi or HQ), so that might be the reason why you cannot find it in the API either.

The flow endpoint's results are not documented anywhere, so you might be right, but I have no way of testing it because I'm on a free plan. It's probably a long shot anyway though, the info the API reports is pretty basic from what I've seen so far.

> Another grey sticker available in the play queue and playbar at the bottom is "Mix" which is displayed e.g. when you start a found song from search which automatically generates a Track Mix then.

I don't know of a way to detect that either, sorry.
